services:
 pingpong-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-12345}:12345"
    restart: unless-stopped
    networks:
      - pingpong_net

networks:
  pingpong_net:
    name: pingpong_net

